create extension if not exists moddatetime schema extensions;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password text not null,
  name text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  phone text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists handle_customers_updated_at on public.customers;
create trigger handle_customers_updated_at
before update on public.customers
for each row
execute procedure extensions.moddatetime(updated_at);
